### ISSUE TITLE
[TODO] Prep for Beta Release

### ISSUE THREAD

**Issue by ShaunSHamilton** [ShaunSHamilton/web3#13]
- [ ] Reset UI `Console` and tests when changing project
- [ ] Refresh UI `Console` when running tests again
- [ ] Await client build before starting server
- [ ] Ensure Camper input does not break (error out) development server
- [ ] Indicate to Camper if development server errors out - tell Camper to `freeCodeCamp: Start`
