### ISSUE TITLE
[TODO] More Beta Prep

### ISSUE THREAD

**Issue by ShaunSHamilton** [ShaunSHamilton/web3#16]
- [x] Collapse JSON output in `Console`
- [x] Congratulations message (indicator that Camper "won");
- [x] Markdown in `Tests`
- [x] Spacing in `Tests`
- [x] Remove list-styling in `Tests`
- [x] Loading screen needs work (extension)
- [x] Simple Browser opens before server is ready
- [x] In-line codeblock overlaps - add better padding, etc.

**Build a Smart Contract in Rust**

- [x] Mention specific file/directory Campers need to work in
- [x] Add `wasm-pack` to `Dockerfile`
- [x] Add `Account`, `Context` structs to **User Stories**
- [x] Mention how to use `JsValue` - how to wrap a Struct in a `JsValue`
- [ ] ~Add `_blank` to external links~ _not possible due to Simple Browser sandbox_
- [x] Remove first test `lib::`
- [x] Mention importing needed imports
- [ ] "If you want to see your contract in action..."
  - [ ] Deploy contract
  - [ ] Run nodes
  - [ ] Test contract
