### ISSUE TITLE
Canaries Release Task List

### ISSUE THREAD

**Issue by moT01** [ShaunSHamilton/web3#39]
1. QA the five projects, checked means they're ready:
- [x] Build a Video Game Marketplace Blockchain
- [x] Build a Fundraising Smart Contract
- [x] Build a Peer-to-Peer Network
- [x] Build a Web3 Client-Side Package for Your dApp
- [x] Build a Smart Contract in Rust

2.
- [x] Fix any significant ShaunOS issues. I'm not sure there are any that really need fixing - seems to be working good.

3. Write explanation on how to run them. Not sure if we just want to post in discord or maybe make a forum post to link to
- [x] Write it
- [x] Post it

**Comment by ShaunSHamilton** [comment]
> Not sure if we just want to post in discord or maybe make a forum post to link to

We probably want to do similar to previous times:
- Write a Gist to share with Canaries
  - Gist will be almost exactly the same as the article
  - Based on feedback, adjust article
- Publish article for release

We need to find out about whether/when we will do a _"Let's Play"_

**Comment by moT01** [comment]
Rough list for ~~article/post~~ gist for running this - feel free to edit:

Prereqs:
docker
vscode
remote containers extension

1. Run Docker Desktop
2. Clone `freeCodeCamp/web3-curriculum`
3. Open repo in its own workspace
4. Build container/open in new container
5. Run `freeCodeCamp: Run Course`. Once it's ready, it will open the simple browser. You may need to refresh it before the home page shows up.
6. Click an available project and follow the instructions to complete it

_Optional Bonus:_
1. Run Docker Desktop
2. `mkdir web3-curriculum && cd web3-curriculum`
3. Run `freeCodeCamp: Open Course`
4. Select `Web3 Curriculum`
5. _first list 4-6_
